baseURL = 'https://alexplescan.com/'
languageCode = 'en-US'
title = 'Alex Plescan'
# forcing a one-word summary ensures that only the first paragraph is ever used
summaryLength = 1 
capitalizeListTitles = false

[params]
description = "Alex Plescan's website"
title = "Alex Plescan"
[params.social]
twitter = "alexplescan"
[params.plausible]
enabled = false
domain = 'alexplescan.com'

[permalinks]
[permalinks.page]
posts = '/posts/:year/:month/:day/:slugorfilename/'

[markup]
[markup.tableOfContents]
startLevel=2
endLevel=2
ordered=true
[markup.highlight]
style = 'tokyonight-night'
[markup.goldmark.renderer]
unsafe = true

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

