language: ruby

rvm:
  - 2.5

script: ./script/ci_build.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors