title: Alex Plescan
email: alex@alexplescan.com
description: Alex Plescan writes blogs here!
url: "https://alexplescan.com"
github_username:  alexpls
permalink: /posts/:year/:month/:day/:title/

markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-feed

defaults:
  -
    scope:
      path: ''
    values:
      author:
        name: 'Alex Plescan'
        email: 'alex@alexplescan.com'
        uri: 'https://alexplescan.com'
