title: Alex Plescan
email: alex@alexplescan.com
description: I'm a web and mobile developer. This is my personal website. 
url: "https://alexplescan.com"
github_username:  alexpls
permalink: /posts/:year/:month/:day/:title/

collections:
  projects:
    output: false
  photos:
    output: false

markdown: kramdown

kramdown:
  input: GFM

show_drafts: false

sass:
  style: compressed

favicon:
  source: /assets/favicon.png
  path: /assets/favicon

defaults:
  -
    scope:
      path: ''
    values:
      author:
        name: 'Alex Plescan'
        email: 'alex@alexplescan.com'
        uri: 'https://alexplescan.com'

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 3
paginate_path: '/posts/pages/:num/'

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - working
  - terraform
  - tsconfig.json
  - package.json
  - yarn.lock
  - webpack.config.js
