title: Alex Plescan
email: alex@alexplescan.com
description: Alex Plescan writes blogs here!
url: "https://alexplescan.com"
github_username:  alexpls
permalink: /posts/:year/:month/:day/:title/

markdown: kramdown

kramdown:
  input: GFM

show_drafts: false

sass:
  style: compressed

defaults:
  -
    scope:
      path: ''
    values:
      author:
        name: 'Alex Plescan'
        email: 'alex@alexplescan.com'
        uri: 'https://alexplescan.com'

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

exclude: [vendor, script, meta]

enable_google_analytics: true

paginate: 3
paginate_path: '/posts/pages/:num/'