baseURL = 'https://alexplescan.com/'
languageCode = 'en-US'
title = 'Alex Plescan'
summaryLength = 20

[params]
description = "Alex Plescan's website"
title = "Alex Plescan"
[params.social]
twitter = "alexplescan"

[markup]
[markup.tableOfContents]
startLevel=2
endLevel=2
ordered=true
[markup.highlight]
style = 'tokyonight-night'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

[markup.goldmark.renderer]
unsafe = true
