# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Continous integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      JEKYLL_ENV: production
    steps:
      - name: Install dependencies
        run: sudo apt-get install libvips libvips-dev
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.3"
          bundler-cache: true
      - name: Test
        run: bundle exec rake test
      - name: Build
        run: bundle exec jekyll build --config _config.yml
      - uses: actions/upload-artifact@v2
        with:
          name: site_build
          path: _site
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    env:
      AWS_REGION: ap-southeast-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: site_build
          path: site_build
      - name: Deploy to S3
        run: |
          aws s3 cp site_build/ s3://alexplescan.com/ --recursive --include "*" --exclude "generated/*" --exclude "assets/fonts/*"
          aws s3 cp site_build/generated/ s3://alexplescan.com/generated/ --recursive --cache-control max-age=31104000
          aws s3 cp site_build/assets/fonts/ s3://alexplescan.com/assets/fonts/ --recursive --cache-control max-age=31104000
      - name: Invalidate CloudFront distribution
        run: aws cloudfront create-invalidation --distribution-id E3NNO0QKNYIJYL --paths "/*"
